### ISSUE TITLE
location of evolution & atmosphere models?

### ISSUE THREAD

**Issue by GailZasowski** [astropy/PopStar#2]
Hi,

I came across PopStar while looking for a code to generate SSPs for a student project, and it looks like it's exactly what we need.  However, I'm not sure where the ancillary data are -- the evolution & atmosphere model grids.  I have the CDBS files for pysynphot from STScI.  PopStar's README gives instructions for downloading the model grids, but the paths (e.g., /g/lu/models/evolution/) don't seem valid.  Would you mind clarifying?  Apologies if I'm missing something obvious!

Thank you,
Gail

**Comment by jluastro** [comment]
Hi Gail,

PopStar isn’t officially released; but we would love to have an alpha-tester! We have been having trouble figuring out an ideal place to make the model grids accessible. For now, we are going to make some tar balls and host them for download here at Berkeley. You can download the models at:

http://www.astro.berkeley.edu/~jlu/popstar/popstar_models.tar.gz
WARNING: The file is currently 7.7Gb zipped and about 13 Gb unzipped.

Once unzipped, you will need to set your environment variables to point to the right location. 

Sincerely,
Jessica Lu

**Comment by GailZasowski** [comment]
Hi Jessica,

Thank you!  I can definitely appreciate the difficulty of hosting such a large file.  I've grabbed it now, but have run into the next problem that I'll post as a new issue.

(Happy to be an alpha-tester!)

Cheers,
Gail
